package lane;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import static lane.accounts.con;
import static lane.accounts.state;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class ceoacc extends javax.swing.JFrame implements ActionListener{
    ImageIcon icon=new ImageIcon("lan.jpg");
    /**
     * Creates new form ceoacc
     */
    public ceoacc() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(icon.getImage());
        acc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ceo account details");
        setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("username");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("password");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("recovery password");

        txt1.setBackground(new java.awt.Color(0, 102, 102));
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        txt2.setBackground(new java.awt.Color(0, 102, 102));

        txt3.setBackground(new java.awt.Color(0, 102, 102));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("change recovery");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("change password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("change username");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("HOME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setForeground(new java.awt.Color(51, 255, 51));
        jButton5.setText("back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            this.dispose();
            change();
        } catch (SQLException ex) {
            Logger.getLogger(ceoacc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ceoacc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        try {
            new lane.mainwin_1().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ceoacc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ceoacc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        try {
            new lane.accounts().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ceoacc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ceoacc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            this.dispose();
            change();
        } catch (SQLException ex) {
            Logger.getLogger(ceoacc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ceoacc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            this.dispose();
            change();
        } catch (SQLException ex) {
            Logger.getLogger(ceoacc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ceoacc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ceoacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ceoacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ceoacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ceoacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ceoacc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    // End of variables declaration//GEN-END:variables

    private void acc() {
    
        try {
                        Class.forName("org.sqlite.JDBC");
                        con = DriverManager.getConnection("jdbc:sqlite:lng.db");
                        
                        state = con.createStatement();
                        ResultSet rs = state.executeQuery("select * from ceo;");
                        
                        if(rs.next()){
                            String c1=rs.getString(1);
                            String c2=rs.getString(2);
                            String c3=rs.getString(3);
                            
                            txt1.setText(c1);
                            txt2.setText(c2);
                            txt3.setText(c3);
                            
                            con.close();
                            state.close();
                            rs.close();
                            
                        }
                       con.close();
                       state.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(lane2.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(lane2.class.getName()).log(Level.SEVERE, null, ex);
                    }
        
    }
    //for firstrun
     public static boolean hasData = false;
    JButton clear1 = new JButton("clear");
    JButton create2 = new JButton("change");
    JButton show1 = new JButton("show");
    JButton hide1 = new JButton("hide");
    JButton bck8 = new JButton("back");
    JTextField name11 = new JTextField();
    JPasswordField pas11 = new JPasswordField();
    JPasswordField pas21 = new JPasswordField();
    JTextField code1 = new JTextField();
    JLabel lnamel1 = new JLabel("user name");
    JLabel pas1l1 = new JLabel("new password");
    JLabel pas2l1 = new JLabel("confirm password");
    JLabel codel1 = new JLabel("enter recovery word");
    JFrame frame3 = new JFrame("change ceo admin account.");
    public void change() throws SQLException, ClassNotFoundException{
        frame3.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        frame3.setSize(350, 300);
        frame3.setResizable(false);
        frame3.setIconImage(icon.getImage());
        frame3.setLayout(null);
        frame3.getContentPane().setBackground(Color.pink);
        
        name11.setBounds(150, 20, 150, 30);
        pas11.setBounds(150, 70, 150, 30);
        pas21.setBounds(150, 120, 150, 30);
        code1.setBounds(150, 170, 150, 30);
        
        lnamel1.setBounds(20, 20, 150, 30);
        pas1l1.setBounds(20, 70, 150, 30);
        pas2l1 .setBounds(20, 120, 150, 30);
        codel1.setBounds(20, 170, 150, 30);
        
        clear1.setBounds(180, 220, 70, 30);
        clear1.setBackground(Color.green);
        clear1.addActionListener(this);
        clear1.setForeground(Color.red);
        
        show1.setBounds(260, 220, 70, 30);
        show1.setBackground(Color.orange);
        show1.addActionListener(this);
        show1.setForeground(Color.blue);
        
        hide1.setBounds(260, 220, 70, 30);
        hide1.setBackground(Color.blue);
        hide1.addActionListener(this);
        hide1.setForeground(Color.orange);
        hide1.setVisible(false);
        
        create2.setBounds(100, 220, 70, 30);
        create2.setBackground(Color.yellow);
        create2.addActionListener(this);
        create2.setForeground(Color.red);
        
        bck8.setBounds(10, 220, 70, 30);
        bck8.setBackground(Color.red);
        bck8.addActionListener(this);
        bck8.setForeground(Color.green);
        
        pas11.setText("");
        name11.setText("");
        pas21.setText("");
        code1.setText("");
        this.setVisible(false);
        
        frame3.add(lnamel1);
        frame3.add(pas1l1);
        frame3.add(pas2l1 );
        frame3.add(codel1);
        frame3.add(name11);
        frame3.add(pas11);
        frame3.add(pas21);
        frame3.add(code1);
        frame3.add(clear1);
        frame3.add(bck8);
        frame3.add(create2);
        frame3.add(hide1);
        frame3.add(show1);
        frame3.setLocationRelativeTo(null);
        frame3.setVisible(true);
        }

    @Override
    public void actionPerformed(ActionEvent e) {
    
    if (e.getSource()==bck8){
                frame3.dispose();
                this.dispose();
                new ceoacc().setVisible(true);
        }
    if (e.getSource()==clear1){
            pas11.setText("");
            name11.setText("");
            pas21.setText("");
            code1.setText("");
        }
    if (e.getSource()==show1){
            hide1.setVisible(true);
            show1.setVisible(false);
            pas11.setEchoChar((char)0);
            pas21.setEchoChar((char)0);
        }
        
        if (e.getSource()==hide1){
            hide1.setVisible(false);
            show1.setVisible(true);
            pas11.setEchoChar('*');
            pas21.setEchoChar('*');
        }
        //for admin crete account(caa)
        if (e.getSource()==create2){
            
            try {
                String a2 = name11.getText();
                String b2 = pas11.getText();
                String d2 = pas21.getText();
                String c2 = code1.getText();
                
                String v2 = txt1.getText();
                con.close();
                
                if(a2.equals("")||b2.equals("")||c2.equals("")||d2.equals("")){
                    JOptionPane.showMessageDialog(null, "please fill all the fields to proceed.");
                }
                else{
                    if(d2.equals(b2)&&d2.length()>=6){
                        
                        try {
                            Class.forName("org.sqlite.JDBC");
                            con = DriverManager.getConnection("jdbc:sqlite:lng.db");
                            
                            state = con.createStatement();
                            state.execute("update ceo \n" +
                                          "set un = \""+a2+"\",\n" +
                                          "    pw = \""+b2+"\",\n" +
                                          "    cd = \""+c2+"\"\n" +
                                          "where un = \""+v2+"\";");
                            
                            state.execute("update adm \n" +
                                          "set un = \""+a2+"\",\n" +
                                          "    pw = \""+b2+"\",\n" +
                                          "    cd = \""+c2+"\"\n" +
                                          "where un = \""+v2+"\";");
                            
                            state.execute("update cmf \n" +
                                          "set un = \""+a2+"\",\n" +
                                          "    pw = \""+b2+"\",\n" +
                                          "    cd = \""+c2+"\"\n" +
                                          "where un = \""+v2+"\";");
                            
                            con.close();
                            state.close();
                            JOptionPane.showMessageDialog(null, "please make sure you don't forget your password");
                            JOptionPane.showMessageDialog(null, "recoverly word will be usefull in case you forget your password");
                            JOptionPane.showMessageDialog(null, "your ceo account changed succecfully");
                            con.close();
                            state.close();
                            frame3.dispose();
                            this.dispose();
                            new ceoacc().setVisible(true);
                            acc();

                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, "username password or recoverly word already used.");
                            ex.printStackTrace();
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(lane2.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "passwords do not match or is too short. \npassword must be more than 6 charactors");
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(lane2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
