/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lane;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class recievestock extends javax.swing.JFrame {
ImageIcon icon=new ImageIcon("lan.jpg");
public static Connection con;
    /**
     * Creates new form recievestock
     */
    public recievestock() {
        initComponents();
        this.setIconImage(icon.getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        in9 = new javax.swing.JTextField();
        in1 = new javax.swing.JTextField();
        in2 = new javax.swing.JTextField();
        in3 = new javax.swing.JTextField();
        in4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sup1 = new javax.swing.JTextField();
        suppn = new javax.swing.JTextField();
        sup3 = new javax.swing.JTextField();
        sup4 = new javax.swing.JTextField();
        sup5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        sub1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        in5 = new javax.swing.JLabel();
        in11 = new javax.swing.JLabel();
        in10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        sup6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        in8 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        sub2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("recieve stock.");
        setResizable(false);

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("*item");

        jLabel2.setText("*quantity");

        jLabel3.setText("*specifics");

        jLabel4.setText("*buyig price");

        jLabel5.setText("*average profit expected");

        in9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in9ActionPerformed(evt);
            }
        });
        in9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in9KeyTyped(evt);
            }
        });

        in1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in1ActionPerformed(evt);
            }
        });
        in1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in1KeyTyped(evt);
            }
        });

        in2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in2ActionPerformed(evt);
            }
        });
        in2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in2KeyTyped(evt);
            }
        });

        in3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in3KeyTyped(evt);
            }
        });

        in4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in4KeyTyped(evt);
            }
        });

        jLabel6.setText("STOCK  DETAILS ");

        jLabel7.setText("SUPPLIER DETAILS");

        jLabel8.setText("name");

        jLabel9.setText("lanego membership");

        jLabel10.setText("*phone number");

        sup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sup1ActionPerformed(evt);
            }
        });

        suppn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppnActionPerformed(evt);
            }
        });

        sup3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sup3ActionPerformed(evt);
            }
        });

        sup4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sup4ActionPerformed(evt);
            }
        });

        sup5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sup5ActionPerformed(evt);
            }
        });

        jLabel11.setText("email adress(optional)");

        jLabel12.setText("supplier company name(optional)");

        jButton2.setText("*annalyse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        sub1.setText("submit stock details only");
        sub1.setEnabled(false);
        sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1ActionPerformed(evt);
            }
        });

        jLabel13.setText("total buying price");

        jLabel14.setText("total expected profit");

        jLabel15.setText("total after sales ksh");

        jButton4.setText("submit suplier details only");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel17.setText("main goods supplied");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel18.setText("NB // please make sure all the details are filled accurately and perfectly.");

        jButton5.setText("paid");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("debt");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        in8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in8ActionPerformed(evt);
            }
        });
        in8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in8KeyTyped(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("*select state of purchase.");

        sub2.setText("submit both details");
        sub2.setEnabled(false);
        sub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub2ActionPerformed(evt);
            }
        });

        jButton3.setText("verify all details.");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton6))
                                    .addComponent(in8)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(in5, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(in11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(in10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(sub1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sup6)
                                    .addComponent(sup1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(suppn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(sup3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(sup4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(sup5, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sub2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(in1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(in3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(jLabel19))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sup3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sup4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sup5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sup6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(in5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(in11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(in8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton5)
                                    .addComponent(jButton6)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(suppn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(in10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                                .addGap(24, 68, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sup1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            this.dispose();
            new lane.mainwin_1().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(recievestock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(recievestock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void in9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in9ActionPerformed

    private void in1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in1ActionPerformed

    private void sup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sup1ActionPerformed

    private void suppnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppnActionPerformed

    private void sup3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sup3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sup3ActionPerformed

    private void sup4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sup4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sup4ActionPerformed

    private void sup5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sup5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sup5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String a = in1.getText();
        String b = in2.getText();
        String c = in3.getText();
        String d = in4.getText();
        java.util.Date now= new java.util.Date();
        SimpleDateFormat form = new SimpleDateFormat("EE   dd / MMMM / Y      h:mm  a");
        String f = form.format(now);
        //String g = in7.getText();
        String h = in8.getText();
        
        if( a.equals("")||b.equals("")||c.equals("")||d.equals("")
                ||f.equals("")||h.equals("")){
            JOptionPane.showMessageDialog(this, "incomplete details, \n please check if all fields\nare filled before adding.");
        }else{
        try{
        int a1 = Integer.parseInt(in4.getText());
        int b1 = Integer.parseInt(in2.getText());
        int c1 = Integer.parseInt(in9.getText());
        if(b1 < 1 || a1 < 1 || c1 < 1){
            JOptionPane.showMessageDialog(this, "invalid details. cannot take negative number or 0");
        }else{
            String d1 = Integer.toString(a1 * b1);
            String e1 = Integer.toString(b1 * c1);
            int g1 = Integer.parseInt(d1);
            int h1 = Integer.parseInt(e1);
            int i1 = g1+h1;
            String f1 = Integer.toString(i1);
            in5.setText(d1);
            in11.setText(e1);
            in10.setText(f1);
            if(f1.length()>0){
                sub1.setEnabled(true);
            }
        }
        }
    catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "invalid price, quantity or profit.");
    }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1ActionPerformed
        takehistonly();
    }//GEN-LAST:event_sub1ActionPerformed

    private void in8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        in8.setText("paid");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        in8.setText("debt");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void in2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in2ActionPerformed

    private void in1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in1KeyTyped
        sub1.setEnabled(false);
        sub2.setEnabled(false);
    }//GEN-LAST:event_in1KeyTyped

    private void in2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in2KeyTyped
        sub1.setEnabled(false);
        sub2.setEnabled(false);
    }//GEN-LAST:event_in2KeyTyped

    private void in3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in3KeyTyped
        sub1.setEnabled(false);
        sub2.setEnabled(false);
    }//GEN-LAST:event_in3KeyTyped

    private void in4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in4KeyTyped
        sub1.setEnabled(false);
        sub2.setEnabled(false);
    }//GEN-LAST:event_in4KeyTyped

    private void in9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in9KeyTyped
        sub1.setEnabled(false);
        sub2.setEnabled(false);
    }//GEN-LAST:event_in9KeyTyped

    private void in8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in8KeyTyped
        sub1.setEnabled(false);
        sub2.setEnabled(false);
    }//GEN-LAST:event_in8KeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        takesuponly();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void sub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub2ActionPerformed
        
       //----------------------basic
        String a = in1.getText();
        String b = in2.getText();
        String c = in3.getText();
        //-----------------------------date
        java.util.Date now1= new java.util.Date();
        SimpleDateFormat form1 = new SimpleDateFormat(" dd / MMMM / Y ");
        String d = form1.format(now1);
        //------------------------------time
        java.util.Date now2= new java.util.Date();
        SimpleDateFormat form2 = new SimpleDateFormat(" h:mm  a");
        String e = form2.format(now2);
        //--------------------------------day
        java.util.Date now= new java.util.Date();
        SimpleDateFormat form = new SimpleDateFormat(" EEEE ");
        String f = form.format(now);
        //----------------------------at price
        String g = in4.getText();
        //----------------------------profit
        String h = in9.getText();
        //----------------------------selling price
        int aaa = Integer.parseInt(g);
        int bbb = Integer.parseInt(h);
        int tot = aaa + bbb;
        String i = Integer.toString(tot);
        //----------------------------collected by
        login.loginpage usr = new login.loginpage();
        String j = usr.user;
        //----------------------------supplier phone number.
        String k = suppn.getText();
        if( a.equals("")||b.equals("")||c.equals("")||d.equals("")||e.equals("")
                ||f.equals("")||g.equals("")||h.equals("")||i.equals("")||j.equals("")||k.equals("")){
            JOptionPane.showMessageDialog(this, "incomplete details, \n please check if all fields\nare filled before adding.");
        }else{
        try {
            //-----------------------+++++++++++++++++++++++++++++++++++++++
        Class.forName("org.sqlite.JDBC");
        con = DriverManager.getConnection("jdbc:sqlite:lng.db");
        //----------------------basic
        String a0 = in1.getText();
        String b0 = in2.getText();
        String c0 = in3.getText();
        //-----------------------------date
        java.util.Date now10= new java.util.Date();
        SimpleDateFormat form10 = new SimpleDateFormat(" dd / MMMM / Y ");
        String d0 = form10.format(now10);
        //------------------------------time
        java.util.Date now20= new java.util.Date();
        SimpleDateFormat form20 = new SimpleDateFormat(" h:mm  a");
        String e0 = form20.format(now20);
        //--------------------------------day
        java.util.Date now0= new java.util.Date();
        SimpleDateFormat form0 = new SimpleDateFormat(" EEEE ");
        String f0 = form0.format(now0);
        //----------------------------at price
        String g0 = in4.getText();
        //----------------------------profit
        String h0 = in9.getText();
        //----------------------------selling price
        int aaa0 = Integer.parseInt(g);
        int bbb0 = Integer.parseInt(h);
        int tot0 = aaa0 + bbb0;
        String i0 = Integer.toString(tot0);
        //----------------------------collected by
        String j0 = usr.user;
        //----------------------------supplier phone number.
        String k0 = suppn.getText();
        if( a0.equals("")||b0.equals("")||c0.equals("")||d0.equals("")||e0.equals("")
                ||f0.equals("")||g0.equals("")||h0.equals("")||i0.equals("")||j0.equals("")||k0.equals("")){
            JOptionPane.showMessageDialog(this, "incomplete details, \n please check if all fields\nare filled before adding.");
        }
        else{
            Statement state3 = con.createStatement();
            state3.execute("insert into stockhist (item3 ,quant3 , spec3, date3, time3, day3, atprice3, profit3, sellp3, collb3, suppn3) \n" +
                    "values(\""+a0+"\",\""+b0+"\",\""+c0+"\", \""+d0+"\",\n" +
                            "\""+e0+"\", \""+f0+"\",\""+g0+"\",\""+h0+"\",\""+i0+"\",\""+j0+"\",\""+k0+"\");");
            state3.close();
            
            Statement state4 = con.createStatement();
            state4.execute("insert into stocksell (item3 ,quant3 , spec3, date3, time3, day3, atprice3, profit3, sellp3, collb3, suppn3) \n" +
                    "values(\""+a0+"\",\""+b0+"\",\""+c0+"\", \""+d0+"\",\n" +
                            "\""+e0+"\", \""+f0+"\",\""+g0+"\",\""+h0+"\",\""+i0+"\",\""+j0+"\",\""+k0+"\");");
            state4.close();
            
            String aa = "0";
            String bb = in5.getText();
            //-----------------------------date
            java.util.Date now4= new java.util.Date();
            SimpleDateFormat form4 = new SimpleDateFormat(" dd/MMMM ");
            String ee = form4.format(now4);
            //-----------------------------date
            java.util.Date now5= new java.util.Date();
            SimpleDateFormat form5 = new SimpleDateFormat(" Y ");
            String ff = form5.format(now5);
            Statement state5 = con.createStatement();
            state5.execute("insert into transhist (ai ,ao , day, tm, month, year) \n" +
                    "values(\""+aa+"\",\""+bb+"\",\""+f+"\", \""+e+"\",\n" +
                            "\""+ee+"\", \""+ff+"\");");
            state5.close();
            
            con.close();
           
        }
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(recievestock.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "invalid price or quantity.");
    }
               //+++++++++++++++++++++++++++++++.................................... 
           try {
        Class.forName("org.sqlite.JDBC");
        con = DriverManager.getConnection("jdbc:sqlite:lng.db");
        String az = sup1.getText();
        String bz = suppn.getText();
        String cz = sup6.getText();
        //-------------------------date added
        java.util.Date now1z= new java.util.Date();
        SimpleDateFormat form1z = new SimpleDateFormat("EE   dd / MMMM / Y      h:mm  a");
        String dz = form1z.format(now1z);
        String ez = sup4.getText();
        String fz = sup5.getText();
        String gz = sup3.getText();
        if( az.equals("")||bz.equals("")||cz.equals("")||dz.equals("")||ez.equals("")
                ||fz.equals("")||gz.equals("")){
            JOptionPane.showMessageDialog(this, "incomplete details, \n please check if all fields\nare filled before adding.");
        }
        else{
            Statement state3 = con.createStatement();
            state3.execute("insert into supplier (sn1 ,pn1 ,mis1,da1 ,ea1 ,comp1 ,ms1 ) \n" +
                    "values(\""+az+"\",\""+bz+"\",\""+cz+"\", \""+dz+"\",\n" +
                            "\""+ez+"\", \""+fz+"\",\""+gz+"\");");
            con.close();
            state3.close();
            JOptionPane.showMessageDialog(this, "supplier details stored succefully.");
            takestockonly();
        }
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(recievestock.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(recievestock.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "invalid price or quantity.");
    }
        }
    }//GEN-LAST:event_sub2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String az = sup1.getText();
        String bz = suppn.getText();
        String cz = sup6.getText();
        //-------------------------date added
        java.util.Date now1z= new java.util.Date();
        SimpleDateFormat form1z = new SimpleDateFormat("EE   dd / MMMM / Y      h:mm  a");
        String dz = form1z.format(now1z);
        String ez = sup4.getText();
        String fz = sup5.getText();
        String gz = sup3.getText();
        if( az.equals("")||bz.equals("")||cz.equals("")||dz.equals("")||ez.equals("")
                ||fz.equals("")||gz.equals("")){
            JOptionPane.showMessageDialog(this, "incomplete details, \n please check if all fields\nare filled before adding.");
        }else{
        if(sub1.isEnabled()) 
            sub2.setEnabled(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recievestock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recievestock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recievestock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recievestock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recievestock().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField in1;
    private javax.swing.JLabel in10;
    private javax.swing.JLabel in11;
    private javax.swing.JTextField in2;
    private javax.swing.JTextField in3;
    private javax.swing.JTextField in4;
    private javax.swing.JLabel in5;
    private javax.swing.JTextField in8;
    private javax.swing.JTextField in9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton sub1;
    private javax.swing.JButton sub2;
    private javax.swing.JTextField sup1;
    private javax.swing.JTextField sup3;
    private javax.swing.JTextField sup4;
    private javax.swing.JTextField sup5;
    private javax.swing.JTextField sup6;
    private javax.swing.JTextField suppn;
    // End of variables declaration//GEN-END:variables

    private void takestockonly() {
          
    try {
        Class.forName("org.sqlite.JDBC");
        con = DriverManager.getConnection("jdbc:sqlite:lng.db");
        String a = in1.getText();
        String b = in2.getText();
        String c = in3.getText();
        String d = in4.getText();
        String e = in5.getText();
        java.util.Date now= new java.util.Date();
        SimpleDateFormat form = new SimpleDateFormat("EE   dd / MMMM / Y      h:mm  a");
        String f = form.format(now);
        //String g = in7.getText();
        login.loginpage usr = new login.loginpage();
        String h = usr.user;
        String h1 = in8.getText();
        if( a.equals("")||b.equals("")||c.equals("")||d.equals("")||e.equals("")
                ||f.equals("")||h.equals("")){
            JOptionPane.showMessageDialog(this, "incomplete details, \n please check if all fields\nare filled before adding.");
        }
        else{
            Statement state3 = con.createStatement();
            state3.execute("insert into stockin (item1 ,quantity1 ,quality1,atprice1 ,totalprice1 ,date1 ,state1 ) \n" +
                    "values(\""+a+"\",\""+Integer.parseInt(b)+"\",\""+c+"\", \""+Integer.parseInt(d)+"\",\n" +
                            "\""+Integer.parseInt(b)*Integer.parseInt(d)+"\", \""+f+"\",\""+h1 +"\");");
            con.close();
            state3.close();
            JOptionPane.showMessageDialog(this, "stock record stored succefully.");
            this.dispose();
            new lane.recievestock().setVisible(true);
        }
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(recievestock.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(recievestock.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "invalid price or quantity.");
    }
            
        }

    private void takehistonly() {
    
         try {
        Class.forName("org.sqlite.JDBC");
        con = DriverManager.getConnection("jdbc:sqlite:lng.db");
        //----------------------basic
        String a = in1.getText();
        String b = in2.getText();
        String c = in3.getText();
        //-----------------------------date
        java.util.Date now1= new java.util.Date();
        SimpleDateFormat form1 = new SimpleDateFormat(" dd / MMMM / Y ");
        String d = form1.format(now1);
        //------------------------------time
        java.util.Date now2= new java.util.Date();
        SimpleDateFormat form2 = new SimpleDateFormat(" h:mm  a");
        String e = form2.format(now2);
        //--------------------------------day
        java.util.Date now= new java.util.Date();
        SimpleDateFormat form = new SimpleDateFormat(" EEEE ");
        String f = form.format(now);
        //----------------------------at price
        String g = in4.getText();
        //----------------------------profit
        String h = in9.getText();
        //----------------------------selling price
        int aaa = Integer.parseInt(g);
        int bbb = Integer.parseInt(h);
        int tot = aaa + bbb;
        String i = Integer.toString(tot);
        //----------------------------collected by
        login.loginpage usr = new login.loginpage();
        String j = usr.user;
        //----------------------------supplier phone number.
        String k = suppn.getText();
        if( a.equals("")||b.equals("")||c.equals("")||d.equals("")||e.equals("")
                ||f.equals("")||g.equals("")||h.equals("")||i.equals("")||j.equals("")||k.equals("")){
            JOptionPane.showMessageDialog(this, "incomplete details, \n please check if all fields\nare filled before adding.");
        }
        else{
            Statement state3 = con.createStatement();
            state3.execute("insert into stockhist (item3 ,quant3 , spec3, date3, time3, day3, atprice3, profit3, sellp3, collb3, suppn3) \n" +
                    "values(\""+a+"\",\""+b+"\",\""+c+"\", \""+d+"\",\n" +
                            "\""+e+"\", \""+f+"\",\""+g+"\",\""+h+"\",\""+i+"\",\""+j+"\",\""+k+"\");");
            state3.close();
            
            Statement state4 = con.createStatement();
            state4.execute("insert into stocksell (item3 ,quant3 , spec3, date3, time3, day3, atprice3, profit3, sellp3, collb3, suppn3) \n" +
                    "values(\""+a+"\",\""+b+"\",\""+c+"\", \""+d+"\",\n" +
                            "\""+e+"\", \""+f+"\",\""+g+"\",\""+h+"\",\""+i+"\",\""+j+"\",\""+k+"\");");
            state4.close();
            
            String aa = "0";
            String bb = in5.getText();
            //-----------------------------date
            java.util.Date now4= new java.util.Date();
            SimpleDateFormat form4 = new SimpleDateFormat(" dd/MMMM ");
            String ee = form4.format(now4);
            //-----------------------------date
            java.util.Date now5= new java.util.Date();
            SimpleDateFormat form5 = new SimpleDateFormat(" Y ");
            String ff = form5.format(now5);
            Statement state5 = con.createStatement();
            state5.execute("insert into transhist (ai ,ao , day, tm, month, year) \n" +
                    "values(\""+aa+"\",\""+bb+"\",\""+f+"\", \""+e+"\",\n" +
                            "\""+ee+"\", \""+ff+"\");");
            state5.close();
            
            con.close();
            
            takestockonly();
        }
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(recievestock.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(recievestock.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "invalid price or quantity.");
    }
    }

    private void takesuponly() {
        
         try {
        Class.forName("org.sqlite.JDBC");
        con = DriverManager.getConnection("jdbc:sqlite:lng.db");
        String a = sup1.getText();
        String b = suppn.getText();
        String c = sup6.getText();
        //-------------------------date added
        java.util.Date now1= new java.util.Date();
        SimpleDateFormat form1 = new SimpleDateFormat("EE   dd / MMMM / Y      h:mm  a");
        String d = form1.format(now1);
        String e = sup4.getText();
        String f = sup5.getText();
        String g = sup3.getText();
        if( a.equals("")||b.equals("")||c.equals("")||d.equals("")||e.equals("")
                ||f.equals("")||g.equals("")){
            JOptionPane.showMessageDialog(this, "incomplete details, \n please check if all fields\nare filled before adding.");
        }
        else{
            Statement state3 = con.createStatement();
            state3.execute("insert into supplier (sn1 ,pn1 ,mis1,da1 ,ea1 ,comp1 ,ms1 ) \n" +
                    "values(\""+a+"\",\""+b+"\",\""+c+"\", \""+d+"\",\n" +
                            "\""+e+"\", \""+f+"\",\""+g+"\");");
            con.close();
            state3.close();
            JOptionPane.showMessageDialog(this, "supplier details stored succefully.");
            this.dispose();
            new lane.recievestock().setVisible(true);
        }
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(recievestock.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(recievestock.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "invalid price or quantity.");
    }
            
        }

}
